version: "3"

services:
  bot:
    image: ghcr.io/drjole/diskettenlaufwerk-anmeldung-bot:latest
    extends:
      file: docker-compose.yml
      service: bot
  scraper:
    image: ghcr.io/drjole/diskettenlaufwerk-anmeldung-bot:latest
    extends:
      file: docker-compose.yml
      service: scraper
  db:
    extends:
      file: docker-compose.yml
      service: db
  redis:
    extends:
      file: docker-compose.yml
      service: redis
