services:
  bot:
    image: ghcr.io/drjole/diskettenlaufwerk-anmeldung-bot:latest
    extends:
      file: docker-compose.yml
      service: bot
    depends_on:
      - db
      - redis

  scraper:
    image: ghcr.io/drjole/diskettenlaufwerk-anmeldung-bot:latest
    extends:
      file: docker-compose.yml
      service: scraper
    depends_on:
      - db
      - redis

  db:
    extends:
      file: docker-compose.yml
      service: db

  redis:
    extends:
      file: docker-compose.yml
      service: redis

volumes:
  bot-db:
