version: "3"

services:
  bot:
    build:
      context: .
      args:
        - BINARY=bot
    depends_on:
      - db
      - redis
    environment:
      RUST_LOG: info
      DATABASE_URL: "postgres://postgres:password@db/frisbee"
      REDIS_URL: "redis://redis:6379"
      TELOXIDE_TOKEN: "${TELOXIDE_TOKEN}"
  scraper:
    build:
      context: .
      args:
        - BINARY=scraper
    depends_on:
      - db
      - redis
    environment:
      RUST_LOG: info
      DATABASE_URL: "postgres://postgres:password@db/frisbee"
      REDIS_URL: "redis://redis:6379"
      TELOXIDE_TOKEN: "${TELOXIDE_TOKEN}"
    profiles:
      - donotstart
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: frisbee
      POSTGRES_PASSWORD: password
  redis:
    image: redis:7
    restart: always
