version: "3"

services:
  bot:
    build: .
    command: /diskettenlaufwerk-anmeldung-bot bot
    restart: always
    depends_on:
      - db
      - redis
    environment:
      RUST_LOG: info
      DATABASE_URL: "postgres://postgres:password@db/frisbee"
      REDIS_URL: "redis://redis:6379"
      TELOXIDE_TOKEN: "${TELOXIDE_TOKEN}"
  scraper:
    build: .
    command: /diskettenlaufwerk-anmeldung-bot scraper
    depends_on:
      - db
      - redis
    environment:
      RUST_LOG: info
      DATABASE_URL: "postgres://postgres:password@db/frisbee"
      REDIS_URL: "redis://redis:6379"
      TELOXIDE_TOKEN: "${TELOXIDE_TOKEN}"
    profiles:
      - donotstart
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: frisbee
      POSTGRES_PASSWORD: password
    volumes:
      - './db:/var/lib/postgresql/data'
  redis:
    image: redis:7
    restart: always
