name: Build and push Docker images

on:
  push:
    branches:
      - "main"

jobs:

  deploy:
    name: Build and push
    runs-on: ubuntu-latest
    concurrency: build
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Docker bot meta
        id: bot_meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/drjole/diskettenlaufwerk-anmeldung-bot-bot
          tags: |
            type=raw,value=latest
      - name: Docker scraper meta
        id: scraper_meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/drjole/diskettenlaufwerk-anmeldung-bot-scraper
          tags: |
            type=raw,value=latest
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push bot image
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            BINARY=bot
          tags: ${{ steps.bot_meta.outputs.tags }}
          labels: ${{ steps.bot_meta.outputs.labels }}
      - name: Build and push scraper image
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            BINARY=scraper
          tags: ${{ steps.scraper_meta.outputs.tags }}
          labels: ${{ steps.scraper_meta.outputs.labels }}
